### ISSUE TITLE
Confusing Function List behavior with Open in Editor: Preserve active document

### ISSUE THREAD

**Issue by timlathy** [vsrad/radeon-asm-tools#313] opened 2022-08-08 18:08 UTC
Normally, the contents of Function List are updated when the editor tab selection is changed. However, when a document is open by the OpenInEditor step, and the "Open in Editor: Preserve active document" option is enabled, the tab focus does not change but the Function List is still updated, leading to confusing behavior where FL displays the contents for an inactive tab and moving the cursor in the active document does not refresh it:

![FL](https://user-images.githubusercontent.com/32609527/183483415-6a1567c4-238b-46c1-9b69-54104ed788ad.gif)

**Comment by Slimakanzer** [comment] 2022-08-08 23:53
This behavior was fixed in recent PR #301. Is it reproducible with latest changes in `master`?

**Comment by johnny-keker** [comment] 2022-08-09 12:07
> This behavior has been fixed in recent PR #301. Is it reproducible with latest changes in `master`?

Looks like this feature didn't make it to the `master`. Will fix that

**Comment by johnny-keker** [comment] 2022-08-09 15:41
Fixed in #315

**Closed** 2022-08-15 19:12 UTC
Labels: urgency low, needs review
